"""add suppliers table

Revision ID: e1f2a3b4c5d6
Revises: a9c940728ad0
Create Date: 2026-01-30 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1f2a3b4c5d6'
down_revision: Union[str, None] = 'a9c940728ad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # suppliers テーブル作成
    op.create_table(
        'suppliers',
        sa.Column('id', sa.String(length=26), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('contact_email', sa.String(length=255), nullable=True),
        sa.Column('contact_phone', sa.String(length=20), nullable=True),
        sa.Column('payout_terms_days', sa.Integer(), nullable=False, server_default='70'),
        sa.Column('default_daily_price', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_suppliers_is_active'), 'suppliers', ['is_active'], unique=False)
    
    # workers テーブルに introducer_supplier_id カラム追加
    op.add_column('workers', sa.Column('introducer_supplier_id', sa.String(length=26), nullable=True))
    op.add_column('workers', sa.Column('introducer_worker_id', sa.String(length=26), nullable=True))
    
    # インデックス追加
    op.create_index(op.f('ix_workers_introducer_supplier_id'), 'workers', ['introducer_supplier_id'], unique=False)
    op.create_index(op.f('ix_workers_introducer_worker_id'), 'workers', ['introducer_worker_id'], unique=False)
    
    # payouts テーブルに supplier_id カラム追加
    op.add_column('payouts', sa.Column('supplier_id', sa.String(length=26), nullable=True))
    
    # worker_id を nullable に変更（SQLite では直接変更不可のため、再作成が必要）
    # SQLite の制約: ALTER COLUMN はサポートされていないため、データ保持のまま対応
    # 運用上、worker_id または supplier_id のいずれかが必須という制約はアプリ層で担保
    
    # インデックス追加
    op.create_index(op.f('ix_payouts_supplier_period'), 'payouts', ['supplier_id', 'period_key'], unique=False)
    
    # Foreign Key は model 定義で管理（SQLite の制約）
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payouts_supplier_period'), table_name='payouts')
    op.drop_column('payouts', 'supplier_id')
    op.drop_index(op.f('ix_workers_introducer_worker_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_introducer_supplier_id'), table_name='workers')
    op.drop_column('workers', 'introducer_worker_id')
    op.drop_column('workers', 'introducer_supplier_id')
    op.drop_index(op.f('ix_suppliers_is_active'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
